name: Release

# This workflow runs when a new GitHub release is published
# It builds the project, attaches schema files to the release,
# and publishes the package to both npm and GitHub Packages

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to upload assets to the release
      packages: write # Needed to publish to GitHub Packages
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registries: |
            @durkinza/challenge-schema:https://registry.npmjs.org/|$NPM_TOKEN
            @durkinza/challenge-schema:https://npm.pkg.github.com/|$GITHUB_TOKEN

      - name: Install dependencies
        run: bun install

      - name: Set version from release tag
        id: set_version
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e 's/refs\/tags\/v//')
          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
            VERSION="$VERSION-beta"
          fi
          echo "Setting package version to $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          jq ".version = \"$VERSION\"" package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Build
        run: bun run build

      - name: Upload schema files to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            challenge.schema.json
            challenge-pack.schema.json
          token: ${{ secrets.GITHUB_TOKEN }}
    

      # - name: Configure npm registry
      #   run: |
      #     echo "@$(echo $GITHUB_REPOSITORY | cut -d/ -f1):registry=https://npm.pkg.github.com" > .npmrc
      #     echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      #     echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      # - name: Publish to NPM with standard tag
      #   run: bun publish --tag ${{ steps.set_version.outputs.VERSION }}
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to GitHub Packages
        run: bun publish --access restricted --tag ${{ steps.set_version.outputs.VERSION }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
